### ISSUE TITLE
Problem building EP7

### ISSUE THREAD

**Issue by pfuentes69** [QuantitativeBytes/qbRayTrace#1]
Hi there. 
This tutorial is simply great and what I needed to get into RT from scratch!
Thanks a lot!

I'd have a question... 
I'm trying to ensure that I can make this code work in my environment (VS Code on Mac) and I found that after EP7 I can't build the code. I can without issues until EP6.
I get errors such as...
`Undefined symbols for architecture x86_64:
  "qbRT::ObjectBase::AssignMaterial(std::__1::shared_ptr<qbRT::MaterialBase> const&)", referenced from:
      qbRT::Scene::Scene() in scene-7e9451.o
  "qbRT::ObjectBase::SetTransformMatrix(qbRT::GTform const&)", referenced from:
      qbRT::Scene::Scene() in scene-7e9451.o
  "qbRT::PointLight::PointLight()", referenced from:
      qbRT::Scene::Scene() in scene-7e9451.o
  "qbRT::PointLight::~PointLight()", referenced from:
      qbRT::Scene::Scene() in scene-7e9451.o
  "qbRT::MaterialBase::ComputeDiffuseColor(std::__1::vector<std::__1::shared_ptr<qbRT::ObjectBase>, std::__1::allocator<std::__1::shared_ptr<qbRT::ObjectBase> > > const&, std::__1::vector<std::__1::shared_ptr<qbRT::LightBase>, std::__1::allocator<std::__1::shared_ptr<qbRT::LightBase> > > const&, std::__1::shared_ptr<qbRT::ObjectBase> const&, qbVector<double> const&, qbVector<double> const&, qbVector<double> const&)", referenced from:
      qbRT::Scene::Render(qbImage&) in scene-7e9451.o
  "qbRT::MaterialBase::~MaterialBase()", referenced from:
      qbRT::SimpleMaterial::SimpleMaterial(qbRT::SimpleMaterial const&) in scene-7e9451.o
  "qbRT::SimpleMaterial::SimpleMaterial()", referenced from:
      qbRT::Scene::Scene() in scene-7e9451.o
  "qbRT::SimpleMaterial::~SimpleMaterial()", referenced from:
      qbRT::Scene::Scene() in scene-7e9451.o
  "qbRT::ObjPlane::ObjPlane()", referenced from:
      qbRT::Scene::Scene() in scene-7e9451.o
  "qbRT::ObjPlane::~ObjPlane()", referenced from:
      qbRT::Scene::Scene() in scene-7e9451.o
  "qbRT::ObjSphere::ObjSphere()", referenced from:
      qbRT::Scene::Scene() in scene-7e9451.o
  "qbRT::ObjSphere::~ObjSphere()", referenced from:
      qbRT::Scene::Scene() in scene-7e9451.o
  "vtable for qbRT::ObjectBase", referenced from:
      qbRT::ObjectBase::ObjectBase(qbRT::ObjectBase const&) in scene-7e9451.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for qbRT::PointLight", referenced from:
      qbRT::PointLight::PointLight(qbRT::PointLight const&) in scene-7e9451.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for qbRT::MaterialBase", referenced from:
      qbRT::MaterialBase::MaterialBase(qbRT::MaterialBase const&) in scene-7e9451.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for qbRT::SimpleMaterial", referenced from:
      qbRT::SimpleMaterial::SimpleMaterial(qbRT::SimpleMaterial const&) in scene-7e9451.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for qbRT::ObjPlane", referenced from:
      qbRT::ObjPlane::ObjPlane(qbRT::ObjPlane const&) in scene-7e9451.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for qbRT::LightBase", referenced from:
      qbRT::LightBase::LightBase(qbRT::LightBase const&) in scene-7e9451.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for qbRT::ObjSphere", referenced from:
      qbRT::ObjSphere::ObjSphere(qbRT::ObjSphere const&) in scene-7e9451.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

What is different in this Episode that prevents me of building?
Thanks again a regards!

**Comment by pfuentes69** [comment]
Hello. 
Never mind... I found the issue... it was my makefile which had to be changed to compile the additional subfolders in qbRayTrace. For some reason I can't make it work with your own makefile...

Also in simplematerial.cpp there was a std::pow(... instead of pow(

**Comment by QuantitativeBytes** [comment]
Hi there,
Great to hear that you got it working in the end! Not sure why it didn't work with the provided makefile though - I've just tested compiling it myself from a fresh clone of the repo and it seemed to work fine. Maybe something I've missed about makefiles? There's certainly a lot I don't know about them. Anyway, thanks for raising the issue, it will be interesting to see if anyone else has a similar problem.

**Comment by QuantitativeBytes** [comment]
Thanks again for raising this issue, I will close it now as resolved but do let me know if you have any other problems. Great to hear that you've been finding the tutorial series useful so far - I hope it continues to be.

**Comment by pfuentes69** [comment]
Thanks a lot for your reactivity. For now I was just trying to compile to foresee issues. I have other problems after Ep 7, as my compiler doesn't like some declarations using templates, but I prefer just start properly the tutorial and when the issues appear I'll try to solve without annoying you too much. Cheers!
